version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: ./api
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    my-app:
      container_name: front
      build:
        context: ./front/tweb-front
        dockerfile: Dockerfile
      volumes:
         - .:/usr/src/app
         - /usr/src/app/node_modules
      ports:
        - '8080:8080'
networks:
    nesjs-network:
